### PR TITLE
add InternVL2-8B video model

### PR DESCRIPTION
**Pull request by chchenhui**
This PR contributes InternVL2 video models. InternVL2 1B, 2B and 8B has passed the local test. For 4B model, there exists a bug in position ids of Phi 3 in the source code ```modeling_phi3.py``` when ```transformers``` package is the latest. See https://github.com/OpenGVLab/InternVL/issues/405 for more details.

### CODE REVIEW

**Comment by jdf-prog** [comment]
Hi, in the `get_info()` function of the adapter, can you change it to `video` or `image`? We don't support other keys like `raw_video`. Also, it will be great if you can also include some information about the model in the `get_info()` function. After fixing these, I think you code should be merged.

**Comment by jdf-prog** [comment]
Hi @chchenhui , I saw there is a modification in `unit_test.py`. This is not allowed. And what's the reason of changing the `param['prompt']` into `param['internvl2_prompt']`? This params is the interface we have previously defined. 
A few things to do:
- you need to change the `param['internvl2_prompt']` back to `param['prompt']`. 
- the 'video` in the params is the encoded video, you should decode it to get the local path. please see [`model_dummy_video.py`](https://github.com/WildVision-AI/LMM-Engines/blob/main/lmm_engines/huggingface/model/dummy_video_model.py#L80) for example.

**Comment by chchenhui** [comment]
Hi @jdf-prog , previously the generated content was very short when using the default prompt text. That's why I tried other prompt text presented in internVL2 demo. I have changed to the default prompt now.

**Comment by jdf-prog** [comment]
> Hi @jdf-prog , previously the generated content was very short when using the default prompt text. That's why I tried other prompt text presented in internVL2 demo. I have changed to the default prompt now.

I see. No worries, just to remind. Feel free to ping me once you finished the debuging. And thanks for the time for contribution!

**Comment by chchenhui** [comment]
hi @jdf-prog , please check the updates. The code has passed local testing and I have resolved the conflicts with the base branch.

**Comment by jdf-prog** [comment]
Thanks for the contribution, the code has already been merged.

**Pull request merged**
